# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install -r requirements.txt

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt